export const ProductActionsTypes = {
    CHANGE_DISPLAYED_PRODUCT: 'CHANGE_DISPLAYED_PRODUCT',
    INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
    DECREMENT_QUANTITY: 'DECREMENT_QUANTITY',
    REQUEST_PRODUCT_LISt: 'REQUEST_TODO_LIST',
    SUCCESS_PRODUCT_LIST: 'SUCCESS_TODO_LIST',
    FAILURE_PRODUCT_LIST: 'FAILURE_TODO_LIST',
}

export const CartActionsType = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    SUB_QUANTITY: 'SUB_QUANTITY',
    ADD_QUANTITY: 'ADD_QUANTITY',
    ADD_SHIPPING: 'ADD_SHIPPING',
    GET_CEP:'GET_CEP',
    CHANGE_CEP_VALUE:'CHANGE_CEP_VALUE',
    CHANCE_FRETE_INFO:'CHANCE_FRETE_INFO',
    GERA_PEDIDO:'GERA_PEDIDO',
    GRAVA_PEDIDO:'GRAVA_PEDIDO',
}

export const ListaDeProdutosActionsType = {
    PRODUTOS_GET_ALL:'PRODUTOS_GET_ALL',
    PRODUTOS_REQUEST_GET_ALL:'PRODUTOS_REQUEST_GET_ALL',
}

export const UserLoginActionsType = {
    CHANGE_USER: 'CHANGE_USER',
    
}

