export const ProductActionsTypes = {
    CHANGE_DISPLAYED_PRODUCT: 'CHANGE_DISPLAYED_PRODUCT',
    INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
    DECREMENT_QUANTITY: 'DECREMENT_QUANTITY'

}

export const CartActionsType = {
    ADD_TO_CART : 'ADD_TO_CART',
    REMOVE_ITEM :'REMOVE_ITEM',
    SUB_QUANTITY : 'SUB_QUANTITY',
    ADD_QUANTITY : 'ADD_QUANTITY',
    ADD_SHIPPING : 'ADD_SHIPPING',
}

